Repository SharylandRobotics/FtcRobotController-IntoTheDeep, pull requests merged in 2025-04, with the labels that each got.

#16 Implemented SensorGoBildaPinpoint and SensorGoBildaPinpointDriver support to the external samples package
  FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/SensorGoBildaPinpoint.java
  FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/SensorGoBildaPinpointDriver.java
Labels: enhancement

#24 ExtenderImpl
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/LLtdc.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/RobotHardware.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/TdcReturnObject.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/TeleOp/FieldCentric.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/TeleOp/LimeTeleOp.java
Labels: enhancement

#26 Field Centric Fix
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/RobotHardware.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/TeleOp/FieldCentric.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/TeleOp/LimeTeleOp.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/visionSystems/LLtdc.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/visionSystems/TdcReturnObject.java
Labels: bug, documentation, enhancement

#32 latest code
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/RobotHardware.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/TeleOp/FieldCentric.java
Labels: enhancement

#35 Added Arm Positions
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/RobotHardware.java
  Team12397/src/main/java/org/firstinspires/ftc/team12397/v2/TeleOp/FieldCentric.java
Labels: bug, enhancement

#38 Auto align to sample
  Team00000/src/main/java/org/firstinspires/ftc/team00000/tuning/TuningOpModes.java
Labels: duplicate
